let REFERENTIEL=[],donnees={audits:[]},profil=null;
const app=document.querySelector('#application'),navigationEntete=document.querySelector('#navigationEntete'),ctaEntete=document.querySelector('#ctaEntete');
const dialogue=document.querySelector('#dialogueAudit'),formulaire=document.querySelector('#formulaireAudit');
const authDialog=document.querySelector('#dialogueConnexion'),authForm=document.querySelector('#formulaireConnexion');
const shareDialog=document.querySelector('#dialoguePartage'),shareForm=document.querySelector('#formulairePartage');
const backend=window.auditBackend;
let vue={auditId:null,indicateur:1,filtre:'tous',criteresOuverts:[]};
const echapper=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const notifier=m=>{const t=document.querySelector('#toast');t.textContent=m;t.classList.add('visible');clearTimeout(t._d);t._d=setTimeout(()=>t.classList.remove('visible'),2600)};
const formatDate=d=>d?new Date(d+'T12:00:00').toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'}):'Non renseignée';
const taille=n=>n<1024?n+' o':n<1048576?(n/1024).toFixed(1)+' Ko':(n/1048576).toFixed(1)+' Mo';
const normaliserUrl=(url='')=>{try{return new URL(/^https?:\/\//i.test(url.trim())?url.trim():`https://${url.trim()}`).href}catch{return''}};
const slugifier=(s='audit')=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'audit';
const auditActif=()=>donnees.audits.find(a=>a.id===vue.auditId);
const progression=a=>{const faits=Object.values(a.indicateurs).filter(i=>i.etat==='termine').length;return{faits,pct:Math.round(faits/32*100),complet:faits===32}};
const urlAudit=(a,n=1)=>`#/audit/${a.id}/${slugifier(a.nom)}/indicateur/${n}`;
const libelleStatutAudit=a=>a.statutAudit==='termine'?'Audit terminé':a.statutAudit==='revision'?'À réviser':'En préparation';
const trouverIndicateur=n=>{for(const c of REFERENTIEL){const i=c.indicateurs.find(x=>x.n===n);if(i)return{...i,critere:c.critere,titreCritere:c.titre}}};

function convertir(r){
  const indicateurs={};for(let n=1;n<=32;n++)indicateurs[n]={etat:'non_commence',notes:'',fichiers:[],liens:[]};
  (r.audit_indicators||[]).forEach(i=>Object.assign(indicateurs[i.indicator_number],{etat:i.status,notes:i.notes}));
  (r.evidence_files||[]).forEach(f=>indicateurs[f.indicator_number].fichiers.push({...f,nom:f.original_name,taille:f.size_bytes,date:f.created_at,auteur:f.profiles?.display_name||f.profiles?.email||'Utilisateur'}));
  (r.evidence_links||[]).forEach(l=>indicateurs[l.indicator_number].liens.push({...l,date:l.created_at}));
  return{id:r.id,nom:r.name,date:r.audit_date,type:r.audit_type,responsable:r.responsible_name||'',statutAudit:r.status,reviseLe:r.reviewed_at,modifie:r.updated_at,indicateurs};
}
async function recharger(){donnees.audits=(await backend.listAudits()).map(convertir)}
async function executer(action,message){try{await action();await recharger();lireRoute();if(message)notifier(message)}catch(e){console.error(e);notifier(e.message||'Une erreur est survenue')}}
function estStaff(){return profil?.is_staff===true}

function configurerEnteteAccueil(){navigationEntete.innerHTML=estStaff()?'<button class="lien-navigation" id="deconnexion">Se déconnecter</button>':'';ctaEntete.innerHTML=estStaff()?'<button class="bouton principal" id="nouvelAudit">Créer un audit</button>':'<button class="bouton principal" id="deconnexion">Se déconnecter</button>';document.querySelector('#nouvelAudit')?.addEventListener('click',ouvrirCreation);document.querySelector('#deconnexion').onclick=()=>backend.signOut()}
function configurerEnteteAudit(){navigationEntete.innerHTML=estStaff()?'<button class="lien-navigation" id="accueilAudits">Accueil des audits</button><button class="lien-navigation" id="deconnexion">Se déconnecter</button>':'';ctaEntete.innerHTML=estStaff()?'<button class="bouton principal" id="partagerAudit">Partager</button>':'<button class="bouton principal" id="deconnexion">Se déconnecter</button>';document.querySelector('#accueilAudits')?.addEventListener('click',allerAccueil);document.querySelector('#partagerAudit')?.addEventListener('click',()=>{shareForm.reset();shareDialog.showModal()});document.querySelector('#deconnexion').onclick=()=>backend.signOut()}
function ouvrirCreation(){formulaire.reset();formulaire.elements.auditId.value='';document.querySelector('#titreDialogue').textContent='Créer un audit';document.querySelector('#enregistrerAudit').textContent='Créer l’audit';dialogue.showModal()}
function ouvrirModification(){const a=auditActif();if(!a)return;Object.assign(formulaire.elements,{ });formulaire.elements.auditId.value=a.id;formulaire.elements.nom.value=a.nom;formulaire.elements.date.value=a.date||'';formulaire.elements.type.value=a.type;formulaire.elements.responsable.value=a.responsable;document.querySelector('#titreDialogue').textContent='Modifier l’audit';document.querySelector('#enregistrerAudit').textContent='Enregistrer';dialogue.showModal()}
function allerAccueil(){location.hash='#/'}
function allerAudit(a,n=1){vue.auditId=a.id;vue.indicateur=n;location.hash=urlAudit(a,n)}
function lireRoute(){const m=location.hash.match(/^#\/audit\/([^/]+)(?:\/[^/]+)?(?:\/indicateur\/(\d+))?/);if(m){const a=donnees.audits.find(x=>x.id===m[1]);if(a){vue.auditId=a.id;vue.indicateur=Math.min(32,Math.max(1,Number(m[2]||1)));afficherAudit();return}}if(!estStaff()){if(donnees.audits.length){allerAudit(donnees.audits[0]);return}configurerEnteteAccueil();app.innerHTML='<section class="erreur-chargement"><h1>Aucun audit accessible</h1><p>Votre invitation est peut-être expirée ou révoquée. Contactez la personne qui vous a invité.</p></section>';return}afficherAccueil()}

function afficherAccueil(){vue.auditId=null;configurerEnteteAccueil();const lignes=donnees.audits.map(a=>{const p=progression(a);return`<article class="ligne-audit" data-audit="${a.id}"><h2>${echapper(a.nom)}</h2><p>${formatDate(a.date)}</p><p>${p.pct===0?'À faire':p.pct===100?'Terminé':'En cours'}</p><p>${echapper(a.type)}</p></article>`}).join('');app.className='audit-home-page';const hero='<section class="page audit-hero"><div class="hero"><div class="hero-gauche"></div><div class="hero-droite"><h1 class="hero-title">Préparation des audits Qualiopi</h1><p class="hero-description">Centralisez les preuves, suivez l’avancement des 32 indicateurs et gardez<br>une trace claire pour chaque audit de Formation Entre-Deux.</p></div></div></section>';const contenu=lignes?`<div class="entete-tableau"><span>Audit</span><span>Date</span><span>Statut</span><span>Type d’audit</span></div>${lignes}`:'<div class="vide"><h3>Aucun audit créé</h3><p>Créez un audit pour commencer à préparer et suivre votre conformité Qualiopi.</p></div>';app.innerHTML=hero+`<section class="liste-audits audits-section ${lignes?'':'audits-section--empty'}">${contenu}</section>`;document.querySelectorAll('[data-audit]').forEach(x=>x.onclick=()=>allerAudit(donnees.audits.find(a=>a.id===x.dataset.audit)))}
function indicateursFiltres(a){return REFERENTIEL.map(c=>({...c,indicateurs:c.indicateurs.filter(i=>vue.filtre==='tous'||a.indicateurs[i.n].etat===vue.filtre)})).filter(c=>c.indicateurs.length)}
function afficherAudit(){
  const a=auditActif();if(!a)return afficherAccueil();app.className='';configurerEnteteAudit();const p=progression(a),info=trouverIndicateur(vue.indicateur),etat=a.indicateurs[vue.indicateur];
  const nav=indicateursFiltres(a).map(c=>`<section class="critere-groupe ${vue.criteresOuverts.includes(String(c.critere))?'ouvert':''}"><button class="critere-nav" data-critere="${c.critere}"><span>Critère ${c.critere} — ${c.titre}</span><span class="chevron"></span></button><div class="critere-indicateurs" ${vue.criteresOuverts.includes(String(c.critere))?'':'hidden'}>${c.indicateurs.map(i=>`<div class="indicateur-nav ${i.n===vue.indicateur?'actif':''}" data-indicateur="${i.n}">${estStaff()?`<span class="pastille ${a.indicateurs[i.n].etat==='en_cours'?'encours':a.indicateurs[i.n].etat==='termine'?'termine':''}"></span>`:''}<span><strong>${i.n}.</strong> ${i.texte.slice(0,70)}…</span></div>`).join('')}</div></section>`).join('');
  const fichiers=etat.fichiers.map(f=>`<div class="fichier"><div class="fichier-nom"><strong>${echapper(f.nom)}</strong><small>${taille(f.taille||0)} · ${echapper(f.auteur)} · ajouté le ${new Date(f.date).toLocaleDateString('fr-FR')}</small></div><div><button class="bouton secondaire petit" data-telecharger="${f.id}">Ouvrir</button>${estStaff()?` <button class="icone-bouton" data-supprimer-fichier="${f.id}">×</button>`:''}</div></div>`).join('')||'<p class="meta">Aucun fichier ajouté.</p>';
  const liens=etat.liens.map(l=>`<div class="fichier"><div class="fichier-nom"><strong>${echapper(l.name||l.url)}</strong><small>${echapper(l.url)}</small></div><div><a class="bouton secondaire petit" href="${echapper(l.url)}" target="_blank" rel="noopener">Ouvrir</a>${estStaff()?` <button class="icone-bouton" data-supprimer-lien="${l.id}">×</button>`:''}</div></div>`).join('')||'<p class="meta">Aucun lien ajouté.</p>';
  const edit=estStaff()?`<section class="bloc"><label>Notes internes<textarea id="notes" placeholder="Décisions, éléments manquants…">${echapper(etat.notes)}</textarea></label></section><section class="bloc"><h3>Pièces justificatives</h3><div class="preuve-types"><div><div class="depot"><p><strong>Ajouter des fichiers</strong><br><span class="meta">PDF, images, documents ou feuilles de calcul</span></p><label class="bouton principal petit">Choisir des fichiers<input id="ajoutFichiers" type="file" multiple hidden></label></div><div class="liste-fichiers">${fichiers}</div></div><div><form class="ajout-lien" id="ajoutLien"><label>Ajouter un lien<input id="urlPreuve" type="url" required></label><label>Nom du lien<input id="nomLien"></label><button class="bouton principal petit">Ajouter le lien</button></form><div class="liste-fichiers">${liens}</div></div></div></section>`:`<section class="bloc"><h3>Notes</h3><p>${echapper(etat.notes)||'Aucune note.'}</p></section><section class="bloc"><h3>Pièces justificatives</h3>${fichiers}${liens}</section>`;
  const revision=p.complet?`<section class="revision ${a.statutAudit==='termine'?'terminee':''}"><h3>Révision finale de l’audit</h3>${a.statutAudit==='termine'?'<p><strong>Audit révisé et terminé</strong>.</p>':estStaff()?'<button class="bouton principal" id="terminerAudit">Confirmer la révision et terminer l’audit</button>':'<p>En attente de la révision finale.</p>'}</section>`:'';
  app.innerHTML=`<section class="audit-page ${estStaff()?'':'audit-viewer'}"><aside class="barre-laterale"><div class="audit-titre"><p class="sur-titre">${echapper(a.type)}</p><h1>${echapper(a.nom)}</h1><p>${formatDate(a.date)}</p><p>Responsable : ${echapper(a.responsable||'Non renseigné')}</p></div>${estStaff()?`<div class="resume"><strong>${p.faits}/32 indicateurs terminés</strong><div class="progression"><span style="width:${p.pct}%"></span></div><small>${p.pct}% · ${libelleStatutAudit(a)}</small></div><div class="filtre"><button data-filtre="tous">Tous</button><button data-filtre="non_commence">À faire</button><button data-filtre="en_cours">En cours</button><button data-filtre="termine">Terminés</button></div>`:''}<nav class="navigation-indicateurs">${nav}</nav>${estStaff()?'<div class="outils-audit"><button class="bouton secondaire petit" id="modifierAudit">Modifier les paramètres</button><button class="bouton secondaire petit" id="dupliquerAudit">Dupliquer cet audit</button><button class="bouton danger petit" id="supprimerAudit">Supprimer cet audit</button></div>':''}</aside><article class="contenu-audit"><div class="en-tete-indicateur"><div><p class="sur-titre">Critère ${info.critere} — ${info.titreCritere}</p><h2>Indicateur ${info.n}</h2></div>${estStaff()?`<div class="statut-indicateur"><select id="etatIndicateur"><option value="non_commence">À faire</option><option value="en_cours">En cours</option><option value="termine">Terminé</option></select></div>`:''}</div><p class="texte-officiel">${info.texte}</p><section class="bloc"><h3>Ce que nous devons démontrer</h3><p>${info.attendu}</p></section><section class="bloc"><h3>Exemples de preuves à fournir</h3><div class="preuves">${info.preuves.map(x=>`<span class="preuve-exemple">${x}</span>`).join('')}</div></section>${edit}${revision}<div class="actions-bas">${vue.indicateur>1?'<button class="bouton secondaire" id="precedent">Indicateur précédent</button>':'<span></span>'}<span class="espace"></span>${vue.indicateur<32?'<button class="bouton principal" id="suivant">Indicateur suivant</button>':''}</div></article></section>`;
  brancherAudit(a,etat);
}
function brancherAudit(a,etat){
  document.querySelector('#modifierAudit')?.addEventListener('click',ouvrirModification);document.querySelectorAll('[data-critere]').forEach(x=>x.onclick=()=>{const id=x.dataset.critere;vue.criteresOuverts=vue.criteresOuverts.includes(id)?vue.criteresOuverts.filter(c=>c!==id):[...vue.criteresOuverts,id];afficherAudit()});document.querySelectorAll('[data-indicateur]').forEach(x=>x.onclick=()=>allerAudit(a,Number(x.dataset.indicateur)));document.querySelectorAll('[data-filtre]').forEach(x=>x.onclick=()=>{vue.filtre=x.dataset.filtre;afficherAudit()});
  const select=document.querySelector('#etatIndicateur');if(select){select.value=etat.etat;select.onchange=e=>executer(()=>backend.updateIndicator(a.id,vue.indicateur,{status:e.target.value}),'Statut mis à jour')}
  document.querySelector('#notes')?.addEventListener('change',e=>executer(()=>backend.updateIndicator(a.id,vue.indicateur,{notes:e.target.value}),'Notes enregistrées'));
  document.querySelector('#ajoutFichiers')?.addEventListener('change',async e=>{for(const f of e.target.files)await executer(()=>backend.upload(a.id,vue.indicateur,f),'Preuve ajoutée')});
  document.querySelector('#ajoutLien')?.addEventListener('submit',e=>{e.preventDefault();const u=normaliserUrl(document.querySelector('#urlPreuve').value);if(u)executer(()=>backend.addLink(a.id,vue.indicateur,document.querySelector('#nomLien').value.trim(),u),'Lien ajouté')});
  document.querySelectorAll('[data-telecharger]').forEach(x=>x.onclick=async()=>{const f=etat.fichiers.find(y=>y.id===x.dataset.telecharger);location.href=await backend.download(f.storage_path)});
  document.querySelectorAll('[data-supprimer-fichier]').forEach(x=>x.onclick=()=>confirm('Supprimer cette preuve ?')&&executer(()=>backend.removeFile(etat.fichiers.find(y=>y.id===x.dataset.supprimerFichier)),'Preuve supprimée'));
  document.querySelectorAll('[data-supprimer-lien]').forEach(x=>x.onclick=()=>confirm('Supprimer ce lien ?')&&executer(()=>backend.removeLink(x.dataset.supprimerLien),'Lien supprimé'));
  document.querySelector('#precedent')?.addEventListener('click',()=>allerAudit(a,vue.indicateur-1));document.querySelector('#suivant')?.addEventListener('click',()=>allerAudit(a,vue.indicateur+1));document.querySelector('#terminerAudit')?.addEventListener('click',()=>executer(()=>backend.updateAudit(a.id,{status:'termine',reviewed_at:new Date().toISOString()}),'Audit terminé'));document.querySelector('#dupliquerAudit')?.addEventListener('click',async()=>{if(!confirm('Dupliquer cet audit avec ses notes, statuts et liens ?'))return;const button=document.querySelector('#dupliquerAudit');button.disabled=true;try{const copy=await backend.duplicateAudit(a);await recharger();allerAudit(donnees.audits.find(x=>x.id===copy.id));notifier('Audit dupliqué')}catch(e){console.error(e);notifier(e.message||'Duplication impossible');button.disabled=false}});document.querySelector('#supprimerAudit')?.addEventListener('click',()=>confirm('Supprimer définitivement cet audit et toutes ses preuves ?')&&executer(()=>backend.deleteAudit(a.id),'Audit supprimé'));
}

formulaire.addEventListener('submit',async e=>{e.preventDefault();const button=document.querySelector('#enregistrerAudit');if(button.disabled)return;button.disabled=true;const fd=new FormData(formulaire),id=fd.get('auditId'),p={name:fd.get('nom'),audit_date:fd.get('date')||null,audit_type:fd.get('type'),responsible_name:fd.get('responsable')};try{if(id){await backend.updateAudit(id,p);dialogue.close();await recharger();lireRoute();notifier('Paramètres enregistrés')}else{const created=await backend.createAudit(p);dialogue.close();await recharger();const audit=donnees.audits.find(x=>x.id===created.id);if(audit)allerAudit(audit);notifier('Audit créé')}}catch(x){console.error(x);notifier(x.message||'Une erreur est survenue')}finally{button.disabled=false}});
shareForm.addEventListener('submit',async e=>{e.preventDefault();const email=new FormData(shareForm).get('email');try{await backend.invite(auditActif().id,email);shareDialog.close();notifier('Invitation enregistrée. Le destinataire peut demander son lien de connexion.')}catch(x){notifier(x.message)}});
async function traiterAuthentification(mode){const fd=new FormData(authForm),email=fd.get('email'),password=fd.get('password'),message=document.querySelector('#messageAuth');message.className='message-auth';try{if(mode==='magic'){message.textContent='Envoi du lien en cours…';if(!email)throw Error('Saisissez votre adresse email.');await backend.signInWithMagicLink(email);message.classList.add('succes');message.textContent='Si cette adresse correspond à un accès invité, un lien de connexion vient d’être envoyé.'}else if(mode==='signup'){if(!authForm.reportValidity())return;if(!email.trim().toLowerCase().endsWith('@formationentredeux.com'))throw Error('La création de compte est réservée aux membres de Formation Entre-Deux.');message.textContent='Création du compte en cours…';const result=await backend.signUp(email,password);if(result.session){message.classList.add('succes');message.textContent='Compte créé. Connexion en cours…'}else{message.classList.add('succes');message.textContent='Compte créé. Consultez votre boîte email et cliquez sur le lien de confirmation.'}}else{message.textContent='Connexion en cours…';await backend.signIn(email,password)}}catch(x){message.classList.add('erreur');message.textContent=x.message==='User already registered'?'Un compte existe déjà avec cette adresse. Utilisez « Se connecter ».':x.message}}
authForm.addEventListener('submit',e=>{e.preventDefault();traiterAuthentification('signin')});
document.querySelector('#creerAcces').addEventListener('click',()=>traiterAuthentification('signup'));
document.querySelector('#lienConnexion').addEventListener('click',()=>traiterAuthentification('magic'));
document.querySelector('#fermerDialogue').onclick=()=>dialogue.close();document.querySelector('#fermerPartage').onclick=()=>shareDialog.close();document.querySelector('#retourAccueil').onclick=()=>document.body.classList.contains('verrouille')?location.assign('https://formationentredeux.com/'):allerAccueil();window.addEventListener('hashchange',lireRoute);
const zoneDate=document.querySelector('#zoneDateAudit'),champDate=formulaire.elements.date;let ouvertureDateProgrammatique=false;const ouvrirCalendrier=()=>{champDate.focus();if(typeof champDate.showPicker==='function'){try{champDate.showPicker();return}catch{}}ouvertureDateProgrammatique=true;champDate.click();ouvertureDateProgrammatique=false};zoneDate.addEventListener('click',e=>{if(ouvertureDateProgrammatique)return;e.preventDefault();ouvrirCalendrier()});zoneDate.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target===zoneDate){e.preventDefault();ouvrirCalendrier()}});

async function demarrer(session){
  const logo=document.querySelector('#retourAccueil');
  if(!session){document.body.classList.remove('initialisation');document.body.classList.add('verrouille');logo.setAttribute('aria-label','Visiter le site Formation Entre-Deux');navigationEntete.innerHTML='';ctaEntete.innerHTML='';app.className='';app.innerHTML='';document.querySelector('#messageAuth').textContent='';if(!authDialog.open)authDialog.showModal();return}
  authDialog.close();document.body.classList.remove('verrouille');logo.setAttribute('aria-label','Retour à l’accueil des audits');await backend.acceptInvitations();profil=await backend.profile();await recharger();document.body.classList.remove('initialisation');lireRoute();
}
async function initialiser(){if(!backend?.configured){app.textContent='Configuration Supabase indisponible.';return}const r=await fetch('./data/qualiopi.json',{cache:'no-store'});REFERENTIEL=await r.json();backend.onAuth((_e,s)=>demarrer(s).catch(console.error));await demarrer(await backend.session())}
initialiser().catch(e=>{console.error(e);app.innerHTML='<section class="erreur-chargement"><h1>Impossible de charger l’application</h1><p>'+echapper(e.message)+'</p></section>'});
